window.NEXUS_TUTOR_DEFAULTS={version:'0.1.16',gatewayBaseUrl:'https://control-acceso-gateway.shindarked.workers.dev',school:{name:'Instituto Ausbel',lat:null,lng:null},thresholds:{waitingMeters:1000,readyMeters:100,atGateMeters:20},distanceMode:'direct',refreshSeconds:30};

(()=>{
  'use strict';
  const CFG_KEY='nexusTutorConfigV1',TELEMETRY_KEY='nexusTutorTelemetryV1';
  const defaults=window.NEXUS_TUTOR_DEFAULTS;
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}};
  const valid=item=>{if(!item)return false;const lat=Number(item.lat),lng=Number(item.lng);return item.lat!=null&&item.lng!=null&&String(item.lat).trim()!==''&&String(item.lng).trim()!==''&&Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180;};
  try{const stored=read(CFG_KEY,null);if(!stored)return;const school={...(defaults.school||{}),...(stored.school||{})};if(!Array.isArray(stored.destinations)||!stored.destinations.length)return;const destinations=stored.destinations.map((item,index)=>({id:String(item?.id||`dest-${index+1}`),name:String(item?.name||`Destino ${index+1}`),lat:item?.lat??null,lng:item?.lng??null}));let activeId=String(stored.activeDestinationId||destinations[0].id);let index=destinations.findIndex(item=>item.id===activeId);if(index<0){index=0;activeId=destinations[0].id;}let active=destinations[index];if(!valid(active)&&valid(school)){active={...active,name:active.name||school.name||'Destino',lat:Number(school.lat),lng:Number(school.lng)};destinations[index]=active;}else if(!valid(active)&&!valid(school)){const telemetry=read(TELEMETRY_KEY,[]);const match=telemetry.find(item=>item?.destinationId===active.id&&Number.isFinite(Number(item?.destinationLatitude))&&Number.isFinite(Number(item?.destinationLongitude)));if(match){active={...active,lat:Number(match.destinationLatitude),lng:Number(match.destinationLongitude),name:active.name||match.destinationName||'Destino'};destinations[index]=active;}}if(valid(active)||stored.activeDestinationId!==activeId){localStorage.setItem(CFG_KEY,JSON.stringify({...stored,destinations,activeDestinationId:activeId,school:{name:active.name,lat:active.lat,lng:active.lng}}));}}catch{}
})();