(()=>{'use strict';
const C=window.GPS_LAB_CONFIG,$=s=>document.querySelector(s),rank={REQUESTED:0,WAITING:1,READY:2,AT_GATE:3,COMPLETED:4};
const terminal=new Set(['COMPLETED','CANCELLED','EXPIRED']);
let tutor=null,students=[],requests=[],watchId=null,pollTimer=null,countTimer=null,lastPosition=null,currentDistance=null,telemetry=[],log=[],manualMode=false,manualDistance=2000,busy=false;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
async function api(path,options={}){const r=await fetch(C.gatewayUrl+path,{...options,headers:{Accept:'application/json','Content-Type':'application/json',...(options.headers||{})},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Object.assign(new Error(d.error||`HTTP_${r.status}`),{data:d});return d}
function currentStatus(){return requests.map(r=>String(r.status||'REQUESTED').toUpperCase()).sort((a,b)=>(rank[b]??-1)-(rank[a]??-1))[0]||'REQUESTED'}
function activeIds(){return requests.filter(r=>r.requestId&&!terminal.has(String(r.status).toUpperCase())).map(r=>r.requestId)}
function addLog(event,detail=''){log.unshift({at:new Date().toISOString(),event,detail});log=log.slice(0,200);renderLog()}
function addTelemetry(event,extra={}){const p=lastPosition?.coords||{};telemetry.unshift({at:new Date().toISOString(),event,tutorId:tutor?.tutorId||$('#tutorSelect').value,requestIds:requests.map(r=>r.requestId).filter(Boolean),status:currentStatus(),source:manualMode?'manual':'gps',latitude:manualMode?null:(Number.isFinite(p.latitude)?p.latitude:null),longitude:manualMode?null:(Number.isFinite(p.longitude)?p.longitude:null),accuracy:manualMode?null:(Number.isFinite(p.accuracy)?p.accuracy:null),...extra});telemetry=telemetry.slice(0,1000);renderTelemetry()}
function renderLog(){$('#eventLog').innerHTML=log.length?log.map(x=>`<div class="event-item"><span><strong>${esc(x.event)}</strong> ${esc(x.detail)}</span><span class="event-time">${new Date(x.at).toLocaleTimeString('es-MX')}</span></div>`).join(''):'<div class="empty-log">Sin eventos.</div>'}
function renderTelemetry(){$('#telemetry').innerHTML=telemetry.length?telemetry.slice(0,50).map(x=>`<div class="event-item"><span><strong>${esc(x.display||x.event)}</strong></span><span class="event-time">${new Date(x.at).toLocaleTimeString('es-MX')}</span></div>`).join(''):'<div class="empty-log">Sin telemetría.</div>'}
function selected(){return[...document.querySelectorAll('[data-student]:checked')].map(x=>x.value)}
function updateIntentButtons(){const enabled=selected().length>0&&!requests.length&&!busy;$('#trackingIntentBtn').disabled=!enabled;$('#gateIntentBtn').disabled=!enabled}
function renderStudents(){const box=$('#students');box.innerHTML=students.map(s=>`<label class="student-choice"><input data-student type="checkbox" value="${esc(s.studentId)}"><span><strong>${esc(s.name)}</strong><small>${esc(s.pickupLocation?.name||'Punto de recogida')}</small></span></label>`).join('')||'<div class="empty-log">Sin alumnos.</div>';box.querySelectorAll('input').forEach(x=>x.addEventListener('change',updateIntentButtons));updateIntentButtons()}
function pickupPoint(){for(const id of selected()){const s=students.find(x=>String(x.studentId)===String(id)),p=s?.pickupLocation;if(p){const lat=Number(p.lat??p.latitude),lng=Number(p.lng??p.longitude);if(Number.isFinite(lat)&&Number.isFinite(lng))return{lat,lng}}}return null}
function hav(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,p1=r(a),p2=r(c),dp=r(c-a),dl=r(d-b),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function paintDistance(d,accuracy=null){currentDistance=d;$('#distanceValue').textContent=Math.round(d);$('#accuracyValue').textContent=manualMode?'Simulada':(Number.isFinite(accuracy)?'±'+Math.round(accuracy)+' m':'—');$('#lastGps').textContent=new Date().toLocaleTimeString('es-MX');$('#locationSource').textContent=manualMode?'Manual':'GPS';$('#progress').style.width=Math.max(0,Math.min(100,100-d/Math.max(1,C.thresholds.waiting)*100))+'%'}
function renderState(){const s=currentStatus();$('#status').textContent=requests.length?(s==='COMPLETED'?'COMPLETADO':s):'SIN SOLICITUD';$('#status').className='status-pill '+(s==='AT_GATE'||s==='COMPLETED'?'status-gate':s==='READY'?'status-ready':s==='WAITING'?'status-waiting':'status-outside');$('#requestIds').textContent=requests.map(r=>r.requestId).filter(Boolean).join(', ')||'—';for(const [name,id] of Object.entries({REQUESTED:'markRequested',WAITING:'markWaiting',READY:'markReady',AT_GATE:'markGate',COMPLETED:'markComplete'})){const rr=rank[name],cr=rank[s]??-1;$('#'+id).className=rr<cr?'done':rr===cr?'active':''}if(s==='COMPLETED'){$('#message').innerHTML='<strong>Recorrido completado.</strong><br>Que tengas un lindo día.';$('#progress').style.width='100%'}updateIntentButtons()}
function merge(d){for(const item of d.requests||d.results||[]){const id=item.requestId||item.request?.requestId;if(!id)continue;const r=requests.find(x=>x.requestId===id);if(r)r.status=String(item.status||item.request?.status||r.status).toUpperCase()}renderState()}
function stopGps(){if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null;addLog('GPS_STOPPED')}}
function localPosition(pos){lastPosition=pos;const point=pickupPoint();if(!point)return;const d=hav(pos.coords.latitude,pos.coords.longitude,point.lat,point.lng);paintDistance(d,pos.coords.accuracy);addTelemetry('LOCAL_POSITION',{display:`LOCAL_POSITION (${Math.round(d)} m)`,distanceMeters:d})}
function startGps(){if(manualMode||watchId!=null||!navigator.geolocation)return;watchId=navigator.geolocation.watchPosition(localPosition,e=>{addLog('GPS_ERROR',e.message);addTelemetry('GPS_ERROR',{display:`GPS_ERROR → ${e.message}`,error:e.message})},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});addLog('GPS_STARTED')}
function pollDelay(){return C.poll[currentStatus()]||10000}
function stopPolling(){clearTimeout(pollTimer);clearInterval(countTimer);pollTimer=countTimer=null;$('#nextPoll').textContent='—'}
function stopAll(){stopGps();stopPolling()}
function schedulePoll(){stopPolling();if(!activeIds().length)return;const delay=pollDelay(),until=Date.now()+delay;countTimer=setInterval(()=>$('#nextPoll').textContent=Math.max(0,Math.ceil((until-Date.now())/1000))+' s',500);pollTimer=setTimeout(runPoll,delay)}
async function gpsPoll(ids){if(!Number.isFinite(currentDistance)){addLog('GATEWAY_GPS_SKIPPED','Sin ubicación válida');addTelemetry('GATEWAY_GPS_SKIPPED',{display:'GATEWAY_GPS → SIN UBICACIÓN'});return}const body={tutorId:tutor.tutorId,requestIds:ids,distanceMeters:currentDistance},sent=Math.round(currentDistance),data=await api('/api/pickup-requests/gps',{method:'POST',body:JSON.stringify(body)});merge(data);const response=currentStatus();addLog('GATEWAY_GPS',`(${sent} m) → ${response}`);addTelemetry('GATEWAY_GPS',{display:`GATEWAY_GPS (${sent} m) → ${response}`,distanceMeters:currentDistance,responseStatus:response,response:data});if(response==='AT_GATE')stopGps()}
async function statusPoll(ids){const data=await api('/api/pickup-requests/status',{method:'POST',body:JSON.stringify({tutorId:tutor.tutorId,requestIds:ids})});merge(data);const response=currentStatus();addLog('STATUS',`→ ${response}`);addTelemetry('STATUS',{display:`STATUS → ${response}`,responseStatus:response,response:data})}
async function runPoll(){stopPolling();const ids=activeIds();if(!ids.length)return;try{if(currentStatus()==='AT_GATE')await statusPoll(ids);else await gpsPoll(ids);if(currentStatus()==='COMPLETED'){stopAll();renderState();return}if(terminal.has(currentStatus())){stopAll();return}}catch(e){addLog('POLL_ERROR',e.message);addTelemetry('POLL_ERROR',{display:`POLL_ERROR → ${e.message}`,error:e.message})}schedulePoll()}
async function loadTutor(){stopAll();resetLocal(false);const id=$('#tutorSelect').value;$('#tutorName').textContent='Cargando…';try{const d=await api('/api/tutors/'+encodeURIComponent(id));tutor=d.tutor||{tutorId:id};students=Array.isArray(d.students)?d.students:[];$('#tutorName').textContent=tutor.name||tutor.tutorId||id;renderStudents();addLog('TUTOR_LOADED',id)}catch(e){$('#tutorName').textContent='Error';$('#message').textContent=e.message;addLog('ERROR',e.message)}}
async function measureNow(){const point=pickupPoint();if(!point)throw new Error('El punto de recogida no tiene coordenadas.');if(manualMode){paintDistance(manualDistance);return manualDistance}const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));lastPosition=pos;const d=hav(pos.coords.latitude,pos.coords.longitude,point.lat,point.lng);paintDistance(d,pos.coords.accuracy);return d}
function extractCreated(out,ids){return(out.results||out.requests||[]).map((x,i)=>{const q=x.request||x;return{studentId:String(x.studentId||ids[i]||''),requestId:q.requestId||x.requestId,status:String(q.status||x.status||'REQUESTED').toUpperCase(),result:x.result}}).filter(x=>x.requestId)}
async function createIntent(intent){const ids=selected();if(!ids.length||busy)return;busy=true;updateIntentButtons();$('#message').textContent=intent==='AT_GATE'?'Verificando que ya estés en la puerta…':'Preparando tu recorrido…';try{const d=await measureNow(),payload={tutorId:tutor.tutorId,studentIds:ids,mode:'GPS',intent,distanceMeters:d};const out=await api('/api/pickup-requests',{method:'POST',body:JSON.stringify(payload)});requests=extractCreated(out,ids);if(!requests.length){const results=out.results||[];const tooFar=results.some(x=>String(x.result||x.status||'').toUpperCase()==='TOO_FAR');if(tooFar&&intent==='AT_GATE'){addLog('AT_GATE_REJECTED',`(${Math.round(d)} m) → TOO_FAR`);addTelemetry('AT_GATE_REJECTED',{display:`AT_GATE (${Math.round(d)} m) → TOO_FAR`,distanceMeters:d,response:out});$('#message').innerHTML='<strong>Aún estás demasiado lejos de la puerta.</strong><br>Acércate un poco más e inténtalo nuevamente.';return}throw new Error('Gateway no devolvió requestId')}renderState();const response=currentStatus(),label=intent==='AT_GATE'?'AT_GATE':'TRACKING';addLog(label,`(${Math.round(d)} m) → ${response}`);addTelemetry('REQUEST_CREATED',{display:`${label} (${Math.round(d)} m) → ${response}`,intent,distanceMeters:d,responseStatus:response,response:out});if(response==='AT_GATE'){stopGps();$('#message').textContent='La escuela recibió tu aviso. Ya estás en la puerta.'}else{$('#message').textContent='Recorrido iniciado. La escuela recibirá tu avance conforme te acerques.';if(!manualMode)startGps()}schedulePoll()}catch(e){addLog('CREATE_ERROR',e.message);addTelemetry('CREATE_ERROR',{display:`CREATE_ERROR → ${e.message}`,intent,error:e.message,response:e.data||null});$('#message').textContent=e.message}finally{busy=false;updateIntentButtons()}}
function resetLocal(clearDiag=true){stopAll();requests=[];lastPosition=null;currentDistance=null;busy=false;$('#distanceValue').textContent='—';$('#accuracyValue').textContent='—';$('#lastGps').textContent='—';$('#progress').style.width='0%';$('#message').textContent='Selecciona uno o más hijos y elige cómo quieres avisar.';renderState();if(clearDiag){telemetry=[];log=[];renderTelemetry();renderLog()}updateIntentButtons()}
function applyManual(){manualDistance=Math.max(0,Math.round(Number($('#manualDistance').value)||0));$('#manualDistance').value=String(manualDistance);paintDistance(manualDistance);addLog('LOCAL_POSITION',`(${manualDistance} m)`);addTelemetry('LOCAL_POSITION',{display:`LOCAL_POSITION (${manualDistance} m)`,distanceMeters:manualDistance})}
function adjustManual(dir){const step=Math.max(1,Number($('#manualStep').value)||10);$('#manualDistance').value=String(Math.max(0,manualDistance+dir*step));applyManual()}
function toggleManual(){manualMode=$('#manualToggle').checked;$('#manualControls').hidden=!manualMode;$('#locationSource').textContent=manualMode?'Manual':'GPS';if(manualMode){stopGps();manualDistance=Math.max(0,Number($('#manualDistance').value)||0);paintDistance(manualDistance);addLog('LOCATION_SOURCE','Manual')}else{addLog('LOCATION_SOURCE','GPS');if(requests.length&&activeIds().length&&currentStatus()!=='AT_GATE')startGps()}}
async function init(){try{const b=await api('/bootstrap');$('#gatewayBadge').textContent=b.instance?.name||'Gateway OK';$('#gatewayBadge').className='badge badge-ok'}catch(e){$('#gatewayBadge').textContent='Gateway error';$('#message').textContent=e.message}$('#tutorSelect').addEventListener('change',loadTutor);$('#trackingIntentBtn').addEventListener('click',()=>createIntent('TRACKING'));$('#gateIntentBtn').addEventListener('click',()=>createIntent('AT_GATE'));$('#resetBtn').addEventListener('click',()=>resetLocal(true));$('#clearBtn').addEventListener('click',()=>{log=[];renderLog()});$('#manualToggle').addEventListener('change',toggleManual);$('#manualDistance').addEventListener('change',applyManual);$('#manualMinus').addEventListener('click',()=>adjustManual(-1));$('#manualPlus').addEventListener('click',()=>adjustManual(1));$('#downloadBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),version:C.version,tutor,students,requests,locationMode:manualMode?'manual':'gps',currentDistanceMeters:currentDistance,telemetry,log},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexus-tutor-gps-telemetry.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});await loadTutor()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();