(()=>{
'use strict';
const TUTOR_ID='TUT0001';
const cfg=window.NEXUS_TUTOR_DEFAULTS||{};
const base=String(cfg.gatewayBaseUrl||'').replace(/\/$/,'');
const DB_NAME='nexus-tutor';
const DB_VERSION=1;
const STORE='context';
const url=path=>`${base}${path}`;
const getJson=async path=>{const response=await fetch(url(path),{headers:{Accept:'application/json'}});const data=await response.json().catch(()=>null);if(!response.ok||!data?.ok){const error=new Error(data?.error||`HTTP_${response.status}`);error.data=data;throw error;}return data;};
const openDb=()=>new Promise((resolve,reject)=>{if(!('indexedDB'in window)){resolve(null);return;}const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const cachePut=async(key,value)=>{try{const db=await openDb();if(!db)return;await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({value,savedAt:new Date().toISOString()},key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}catch(error){console.warn('TUTOR_CONTEXT_CACHE_WRITE_FAILED',error);}};
const cacheGet=async key=>{try{const db=await openDb();if(!db)return null;const result=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const request=tx.objectStore(STORE).get(key);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);});db.close();return result?.value||null;}catch(error){console.warn('TUTOR_CONTEXT_CACHE_READ_FAILED',error);return null;}};
const findStudent=(context,id)=>context.students.find(student=>String(student.studentId)===String(id))||context.students[0]||null;
const paintLocation=(select,context)=>{const student=findStudent(context,select.value),location=student?.pickupLocation,target=document.getElementById(select.dataset.locationTarget||'');if(target)target.textContent=location?`${location.name} · ${Number(location.latitude).toFixed(6)}, ${Number(location.longitude).toFixed(6)}`:'Sin ubicación de salida';if(select.closest('#tab-gps')&&location?.proximity){const waiting=document.querySelector('[data-waiting-label]'),ready=document.querySelector('[data-ready-label]'),gate=document.querySelector('[data-gate-label]');if(waiting)waiting.textContent=`${location.proximity.waitingMeters} m`;if(ready)ready.textContent=`${location.proximity.readyMeters} m`;if(gate)gate.textContent=`${location.proximity.atGateMeters} m`;}};
const fillSelect=(select,context)=>{select.replaceChildren(...context.students.map(student=>{const option=document.createElement('option');option.value=String(student.studentId);option.textContent=student.name;return option;}));paintLocation(select,context);select.onchange=()=>paintLocation(select,context);};
const paintInstance=instance=>document.querySelectorAll('[data-instance-name]').forEach(node=>node.textContent=instance?.name||'Institución');
const paintProfile=context=>{document.querySelectorAll('[data-tutor-name]').forEach(node=>node.textContent=context.tutor?.name||context.tutor?.tutorId||TUTOR_ID);document.querySelectorAll('[data-student-select]').forEach(select=>fillSelect(select,context));document.querySelectorAll('[data-context-state]').forEach(node=>{node.textContent=`${context.students.length} alumno${context.students.length===1?'':'s'} autorizado${context.students.length===1?'':'s'}`;node.className='badge badge-ok';});};
const paintError=error=>document.querySelectorAll('[data-context-state]').forEach(node=>{node.textContent=`Gateway: ${error.message}`;node.className='badge badge-warn';});
const start=async()=>{let instance=null;try{const bootstrap=await getJson('/bootstrap');instance=bootstrap.instance||null;paintInstance(instance);cachePut('bootstrap',bootstrap);window.NEXUS_TUTOR_CONTEXT.current={instance,gateway:bootstrap.gateway||null,tutor:null,students:[]};window.dispatchEvent(new CustomEvent('nexus:tutor-bootstrap',{detail:bootstrap}));}catch(error){const cached=await cacheGet('bootstrap');if(cached){instance=cached.instance||null;paintInstance(instance);window.NEXUS_TUTOR_CONTEXT.current={instance,gateway:cached.gateway||null,tutor:null,students:[]};}else{paintError(error);console.warn('TUTOR_BOOTSTRAP_NOT_AVAILABLE',error);return null;}}
try{const profile=await getJson(`/api/tutor/me?tutorId=${encodeURIComponent(TUTOR_ID)}`);const context={instance,gateway:window.NEXUS_TUTOR_CONTEXT.current?.gateway||null,tutor:profile.tutor||null,students:Array.isArray(profile.students)?profile.students:[]};window.NEXUS_TUTOR_CONTEXT.current=context;paintProfile(context);cachePut(`tutor:${TUTOR_ID}`,profile);window.dispatchEvent(new CustomEvent('nexus:tutor-context',{detail:context}));return context;}catch(error){const cached=await cacheGet(`tutor:${TUTOR_ID}`);if(cached){const context={instance,gateway:window.NEXUS_TUTOR_CONTEXT.current?.gateway||null,tutor:cached.tutor||null,students:Array.isArray(cached.students)?cached.students:[]};window.NEXUS_TUTOR_CONTEXT.current=context;paintProfile(context);window.dispatchEvent(new CustomEvent('nexus:tutor-context',{detail:context}));return context;}paintError(error);console.warn('TUTOR_PROFILE_NOT_AVAILABLE',error);return null;}};
window.NEXUS_TUTOR_CONTEXT={TUTOR_ID,current:null,start,findStudent,cacheGet,cachePut};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();