(()=>{'use strict';
const $=s=>document.querySelector(s);const state={instance:null,tutor:null,students:[],requests:[],mode:'GPS',timer:null,watching:false};
const TERMINAL=new Set(['COMPLETED','CANCELLED','EXPIRED']);
function setMessage(text,kind=''){const el=$('#flowMessage');if(!el)return;el.textContent=text;el.className=`helper ${kind}`;}
function selectedStudents(){return [...document.querySelectorAll('[data-flow-student]:checked')].map(x=>x.value);}
function renderStudents(){const box=$('#flowStudents');box.replaceChildren(...state.students.map(s=>{const label=document.createElement('label');label.className='student-choice';const input=document.createElement('input');input.type='checkbox';input.value=String(s.studentId);input.dataset.flowStudent='';const body=document.createElement('span');body.className='student-choice-body';const strong=document.createElement('strong');strong.textContent=s.name;const small=document.createElement('small');small.textContent=s.pickupLocation?.name||'Punto de recogida';body.append(strong,small);label.append(input,body);return label;}));updateCreate();}
function updateCreate(){const b=$('#flowCreate');if(b)b.disabled=!state.tutor||!selectedStudents().length;}
async function loadTutor(){const id=$('#flowTutor').value;setMessage('Cargando tutor…');try{const data=await GatewayClient.tutor(id);state.tutor=data.tutor||{tutorId:id};state.students=Array.isArray(data.students)?data.students:[];$('#flowTutorName').textContent=state.tutor.name||state.tutor.tutorId||id;renderStudents();setMessage(`${state.students.length} alumno${state.students.length===1?'':'s'} disponible${state.students.length===1?'':'s'}.`);}catch(e){state.tutor=null;state.students=[];renderStudents();setMessage(e.message,'error');}}
function activeIds(){return state.requests.filter(r=>r.requestId&&!TERMINAL.has(String(r.status||'').toUpperCase())).map(r=>r.requestId);}
function renderRequests(){const box=$('#flowRequests');if(!state.requests.length){box.innerHTML='<div class="empty-log">Sin solicitud activa.</div>';return;}box.replaceChildren(...state.requests.map(r=>{const row=document.createElement('div');row.className='tracking-row';const name=document.createElement('strong');name.textContent=r.studentName||r.studentId;const status=document.createElement('span');status.textContent=r.status||r.result||'REQUESTED';row.append(name,status);return row;}));const status=state.requests.map(r=>String(r.status||'').toUpperCase()).find(Boolean)||'REQUESTED';$('#flowStatus').textContent=status;$('#flowStatus').className=`status-pill ${status==='AT_GATE'?'status-gate':status==='READY'?'status-ready':status==='WAITING'?'status-waiting':'status-outside'}`;}
function merge(result){for(const item of result?.requests||result?.results||[]){const r=state.requests.find(x=>x.requestId===item.requestId);if(r)r.status=item.status||r.status;}renderRequests();}
async function poll(){clearTimeout(state.timer);const ids=activeIds();if(!ids.length)return;try{merge(await GatewayClient.pickupStatus(state.tutor.tutorId,ids));if(state.requests.some(r=>String(r.status).toUpperCase()==='COMPLETED'))setMessage('Solicitud completada. Que tengas un buen día.');}catch(e){setMessage(e.message,'error');}const status=state.requests.map(r=>String(r.status||'').toUpperCase());if(status.every(x=>TERMINAL.has(x)))return;const delay=status.includes('AT_GATE')?10000:status.includes('READY')?10000:status.includes('WAITING')?30000:60000;state.timer=setTimeout(poll,delay);}
function pickupLocation(){const ids=selectedStudents();for(const id of ids){const s=state.students.find(x=>String(x.studentId)===String(id));const p=s?.pickupLocation;if(p&&Number.isFinite(Number(p.lat??p.latitude))&&Number.isFinite(Number(p.lng??p.longitude)))return{lat:Number(p.lat??p.latitude),lng:Number(p.lng??p.longitude)};}return null;}
async function sendGps(position){const ids=activeIds();if(!ids.length)return;const dest=pickupLocation();if(!dest)return;const m=await NEXUS_TUTOR_DISTANCE.measure({position,school:dest,mode:'direct'});$('#flowDistance').textContent=`${Math.round(m.meters)} m`;merge(await GatewayClient.updatePickupGps(state.tutor.tutorId,ids,m.meters));if(state.requests.some(r=>String(r.status).toUpperCase()==='AT_GATE')){NEXUS_TUTOR_LOCATION.stop();state.watching=false;}}
function startGps(){if(state.watching)return;state.watching=true;NEXUS_TUTOR_LOCATION.watch({options:{enableHighAccuracy:true,maximumAge:5000,timeout:15000},onPosition:p=>sendGps(p).catch(e=>setMessage(e.message,'error')),onError:e=>setMessage(e.message||'GPS no disponible','error')});}
async function create(){const ids=selectedStudents();if(!ids.length)return;const payload={tutorId:state.tutor.tutorId,studentIds:ids,mode:state.mode};if(state.mode==='ETA')payload.etaMinutes=Number($('#flowEta').value||10);if(state.mode==='GPS'){const pos=await NEXUS_TUTOR_LOCATION.fresh();const dest=pickupLocation();if(!dest)throw new Error('Punto de recogida sin coordenadas.');const m=await NEXUS_TUTOR_DISTANCE.measure({position:pos,school:dest,mode:'direct'});payload.distanceMeters=m.meters;$('#flowDistance').textContent=`${Math.round(m.meters)} m`;}const result=await GatewayClient.createPickupRequests(payload);state.requests=(result.results||[]).map(item=>{const s=state.students.find(x=>String(x.studentId)===String(item.studentId)),q=item.request||{};return{studentId:String(item.studentId),studentName:s?.name||item.studentId,requestId:q.requestId||item.requestId||null,status:q.status||item.status||(item.result==='CREATED'?'REQUESTED':item.result),result:item.result};});renderRequests();$('#flowSetup').hidden=true;$('#flowTracking').hidden=false;setMessage('Solicitud enviada al Gateway.');if(state.mode==='GPS')startGps();poll();}
function reset(){clearTimeout(state.timer);state.timer=null;NEXUS_TUTOR_LOCATION?.stop?.();state.watching=false;state.requests=[];$('#flowTracking').hidden=true;$('#flowSetup').hidden=false;$('#flowDistance').textContent='—';$('#flowStatus').textContent='SIN SOLICITUD';renderRequests();setMessage('Listo para iniciar una nueva prueba.');}
async function init(){try{const b=await GatewayClient.bootstrap();state.instance=b.instance||null;$('#flowInstance').textContent=state.instance?.name||'Institución';}catch(e){setMessage(e.message,'error');}$('#flowTutor').addEventListener('change',loadTutor);$('#flowStudents').addEventListener('change',updateCreate);document.querySelectorAll('[name="pickupMode"]').forEach(x=>x.addEventListener('change',()=>{state.mode=document.querySelector('[name="pickupMode"]:checked').value;$('#etaOptions').hidden=state.mode!=='ETA';}));$('#flowCreate').addEventListener('click',()=>create().catch(e=>setMessage(e.message,'error')));$('#flowReset').addEventListener('click',reset);loadTutor();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();